# Site settings
title: The Markup Declaration
email: info@markupdeclaration.org
description: >-
  The Markup Declaration is a movement for revitalizing and
  formalizing our understanding of declarative markup.
baseurl: ""
url: "http://localhost:4000"
twitter_username: markupdec
github_username:  markupdeclaration

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
